nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:8080', 'http://localhost:3000', 'http://127.0.0.1:8080', 'https://localhost:8080', 'https://127.0.0.1:8080', 'http://127.0.0.1:8000', 'https://127.0.0.1:8000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/': true
